name: shopyar
description: "ShopYar woocommerce manager"

publish_to: 'none'

version: 1.0.3+3

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  pdf:
  printing:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.2.2
  flutter_bloc: ^9.0.0
  bloc: ^9.0.0
  get_it: ^8.0.3
  shimmer: ^3.0.0
  dio: ^5.8.0
  equatable: ^2.0.5
  jdate: ^0.9.0
  persian_datetime_picker: ^3.1.0
  http: ^1.3.0
  fl_chart: ^0.70.2
  dropdown_button2: ^2.1.3
  auto_size_text: ^3.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  shamsi_date: ^1.0.4
  pdf: ^3.11.2
  path_provider: ^2.1.5
  share_plus: ^10.1.4
  open_file: ^3.5.10
  printing: ^5.11.0
  permission_handler: ^11.3.1
  flutter_svg: ^2.0.15
  flutter_spinkit: ^5.2.1
  dotted_line: ^3.2.3
  flutter_advanced_switch: ^3.1.0
  image_picker: ^1.2.0
  file_picker: ^8.0.0
  http_parser: ^4.1.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/icons/
    - assets/

  fonts:
    - family: IRANSansWeb
      fonts:
        - asset: assets/fonts/IRANSansWeb.ttf

    - family: Vazir
      fonts:
        - asset: assets/fonts/Vazir.ttf

    - family: Bnazanin
      fonts:
         - asset: assets/fonts/B-NAZANIN.ttf

    - family: Byekan
      fonts:
         - asset: assets/fonts/Yekan.ttf

    - family: NotoSansArabic
      fonts:
        - asset: assets/fonts/NotoSansArabic-Medium.ttf
